plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}


publishing {
    publications {
        jcef(MavenPublication) {
            groupId = 'org.eu.hanana'
            artifactId = 'jcef-api'
            version = '141.0.10'
            artifact(file("libs/jcef-api.jar"))
        }
    }
    repositories {
        mavenLocal()
    }
}
subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_name-$project.name"
    }
    tasks.register('signFinalJar') {
        dependsOn tasks.remapJar

        doLast {
            def inputJar = tasks.remapJar.archiveFile.get().asFile
            def signedJar = new File(
                    inputJar.parent,
                    inputJar.name.replace(".jar", "-signed.jar")
            )

            exec {
                commandLine(
                        "jarsigner",
                        "-keystore", "${rootProject.projectDir}/hanana.jks",
                        '-keypass', '12345678q',
                        "-storepass", "12345678q",
                        "-signedjar", signedJar.absolutePath,
                        inputJar.absolutePath,
                        "hananaapps"
                )
            }
        }
    }
    tasks.processResources{
        //dependsOn("publishJcefToMavenLocal")
    }
    tasks.build {
        //dependsOn tasks.signJar
        //dependsOn("publishJcefToMavenLocal")
        finalizedBy tasks.signFinalJar
    }
    configurations.configureEach {
        exclude group: "me.friwi", module: "jcef-api"
    }
    repositories {
        maven {
            url 'https://maven.aliyun.com/repository/public/'
        }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        maven {
            url 'https://maven.hanana2.link:2053/releases'
        }
    }

    dependencies {

        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.layered {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.minecraft_version}:2024.11.17")
        }
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Add repositories to publish to here.
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}
